# Generated by Django 3.0.5 on 2020-07-23 17:31

import comments.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedComment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('releaseTime', models.DateTimeField(auto_now=True)),
                ('rootCommentID', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RootComment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('releaseTime', models.DateTimeField(auto_now=True)),
                ('commentTags', models.CharField(max_length=256)),
                ('derivedComments', djongo.models.fields.ArrayField(model_container=comments.models.DerivedComment)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
