# Generated by Django 3.0.5 on 2020-07-23 19:31

import comments.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcomment',
            name='derivedComments',
            field=djongo.models.fields.ArrayField(model_container=comments.models.DerivedComment, null=True),
        ),
    ]
